# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_create_channel(self) -> None:
        """Test case for create_channel

        Create Channel
        """
        pass

    def test_delete_channel(self) -> None:
        """Test case for delete_channel

        Delete Channel
        """
        pass

    def test_get_channel_by_id(self) -> None:
        """Test case for get_channel_by_id

        Get Channel By Id
        """
        pass

    def test_get_channel_by_id_or_name(self) -> None:
        """Test case for get_channel_by_id_or_name

        Get Channel By Id Or Name
        """
        pass

    def test_get_channels_of_current_user(self) -> None:
        """Test case for get_channels_of_current_user

        Get Channels Of Current User
        """
        pass

    def test_get_channels_of_user(self) -> None:
        """Test case for get_channels_of_user

        Get Channels Of User
        """
        pass

    def test_get_channels_of_user_users_channels_of_user_id_get(self) -> None:
        """Test case for get_channels_of_user_users_channels_of_user_id_get

        Get Channels Of User
        """
        pass

    def test_get_current_user(self) -> None:
        """Test case for get_current_user

        Get Current User
        """
        pass

    def test_get_user_by_id(self) -> None:
        """Test case for get_user_by_id

        Get User By Id
        """
        pass

    def test_get_users_of_channel(self) -> None:
        """Test case for get_users_of_channel

        Get Users Of Channel
        """
        pass

    def test_join_channel(self) -> None:
        """Test case for join_channel

        Join Channel
        """
        pass

    def test_join_channel_by_email(self) -> None:
        """Test case for join_channel_by_email

        Join Channel By Email
        """
        pass

    def test_leave_channel(self) -> None:
        """Test case for leave_channel

        Leave Channel
        """
        pass

    def test_update_channel(self) -> None:
        """Test case for update_channel

        Update Channel
        """
        pass


if __name__ == '__main__':
    unittest.main()
