# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.webhook_log import WebhookLog

class TestWebhookLog(unittest.TestCase):
    """WebhookLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookLog:
        """Test WebhookLog
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookLog`
        """
        model = WebhookLog()
        if include_optional:
            return WebhookLog(
                id = '',
                description = '',
                invoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status_code = 56,
                request_url = '',
                webhook_method = '',
                successful = True,
                error_message = '',
                response_body = '',
                response_headers = {
                    'key' : null
                    },
                request_headers = {
                    'key' : null
                    },
                payload = {
                    'key' : null
                    },
                organization_id = '',
                action_history_id = ''
            )
        else:
            return WebhookLog(
                description = '',
                status_code = 56,
                request_url = '',
                webhook_method = '',
                successful = True,
        )
        """

    def testWebhookLog(self):
        """Test WebhookLog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
