# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.mail_templates_with_defaults import MailTemplatesWithDefaults

class TestMailTemplatesWithDefaults(unittest.TestCase):
    """MailTemplatesWithDefaults unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailTemplatesWithDefaults:
        """Test MailTemplatesWithDefaults
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailTemplatesWithDefaults`
        """
        model = MailTemplatesWithDefaults()
        if include_optional:
            return MailTemplatesWithDefaults(
                module_templates = [
                    ugc_guard_python.models.mail_template.MailTemplate(
                        subject = '', 
                        body = '', 
                        type = 'report_created_admin', 
                        id = '', 
                        module_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                default_templates = [
                    ugc_guard_python.models.mail_template_base.MailTemplateBase(
                        subject = '', 
                        body = '', 
                        type = 'report_created_admin', )
                    ]
            )
        else:
            return MailTemplatesWithDefaults(
        )
        """

    def testMailTemplatesWithDefaults(self):
        """Test MailTemplatesWithDefaults"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
