# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.report_log_with_invoker import ReportLogWithInvoker

class TestReportLogWithInvoker(unittest.TestCase):
    """ReportLogWithInvoker unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportLogWithInvoker:
        """Test ReportLogWithInvoker
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportLogWithInvoker`
        """
        model = ReportLogWithInvoker()
        if include_optional:
            return ReportLogWithInvoker(
                id = '',
                created_at = '',
                message = '',
                content = {
                    'key' : null
                    },
                log_type = 'created',
                invoker_id = '',
                organization_id = '',
                report_id = '',
                report_invoker = ugc_guard_python.models.user_base.UserBase(
                    id = '', 
                    username = '', 
                    email = '', 
                    name = '', 
                    avatar_id = '', 
                    avatar_url = '', )
            )
        else:
            return ReportLogWithInvoker(
                report_id = '',
        )
        """

    def testReportLogWithInvoker(self):
        """Test ReportLogWithInvoker"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
