# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.main_content_sender import MainContentSender

class TestMainContentSender(unittest.TestCase):
    """MainContentSender unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MainContentSender:
        """Test MainContentSender
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MainContentSender`
        """
        model = MainContentSender()
        if include_optional:
            return MainContentSender(
                id = '',
                module_id = '',
                unique_partner_id = '',
                name = '',
                email = '',
                phone = '',
                extra_data = {
                    'key' : null
                    }
            )
        else:
            return MainContentSender(
                module_id = '',
        )
        """

    def testMainContentSender(self):
        """Test MainContentSender"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
