# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.types_api import TypesApi


class TestTypesApi(unittest.TestCase):
    """TypesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TypesApi()

    def tearDown(self) -> None:
        pass

    def test_create_type(self) -> None:
        """Test case for create_type

        Create Type
        """
        pass

    def test_delete_type(self) -> None:
        """Test case for delete_type

        Delete Type
        """
        pass

    def test_get_type_action_secret(self) -> None:
        """Test case for get_type_action_secret

        Get Type Action Secret
        """
        pass

    def test_get_type_by_id(self) -> None:
        """Test case for get_type_by_id

        Get Type By Id
        """
        pass

    def test_get_types_for_module(self) -> None:
        """Test case for get_types_for_module

        Get Types For Module
        """
        pass

    def test_update_type(self) -> None:
        """Test case for update_type

        Update Type
        """
        pass


if __name__ == '__main__':
    unittest.main()
