# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.ai_api import AiApi


class TestAiApi(unittest.TestCase):
    """AiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AiApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_ai_models(self) -> None:
        """Test case for get_all_ai_models

        Get All Ai Models
        """
        pass

    def test_get_all_ai_usage_for_organization(self) -> None:
        """Test case for get_all_ai_usage_for_organization

        Get All Ai Usage For Organization
        """
        pass

    def test_get_all_monthly_ai_usage_for_organization(self) -> None:
        """Test case for get_all_monthly_ai_usage_for_organization

        Get All Monthly Ai Usage For Organization
        """
        pass

    def test_get_monthly_ai_usage_for_organization_model(self) -> None:
        """Test case for get_monthly_ai_usage_for_organization_model

        Get Monthly Ai Usage For Organization And Model
        """
        pass


if __name__ == '__main__':
    unittest.main()
