# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.identity_providers_api import IdentityProvidersApi


class TestIdentityProvidersApi(unittest.TestCase):
    """IdentityProvidersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IdentityProvidersApi()

    def tearDown(self) -> None:
        pass

    def test_add_identity_provider(self) -> None:
        """Test case for add_identity_provider

        Add Identity Provider
        """
        pass

    def test_get_identity_provider(self) -> None:
        """Test case for get_identity_provider

        Get Identity Provider
        """
        pass

    def test_list_enabled_identity_providers(self) -> None:
        """Test case for list_enabled_identity_providers

        List Enabled Identity Providers
        """
        pass

    def test_list_identity_providers(self) -> None:
        """Test case for list_identity_providers

        List Identity Providers
        """
        pass

    def test_login_for_access_token(self) -> None:
        """Test case for login_for_access_token

        Login For Access Token
        """
        pass

    def test_oidc_callback(self) -> None:
        """Test case for oidc_callback

        Oidc Callback
        """
        pass

    def test_oidc_login(self) -> None:
        """Test case for oidc_login

        Oidc Login
        """
        pass

    def test_prepare_email_for_identity_providers(self) -> None:
        """Test case for prepare_email_for_identity_providers

        Prepare Email For Identity Providers
        """
        pass

    def test_prepare_organization_for_identity_providers(self) -> None:
        """Test case for prepare_organization_for_identity_providers

        Prepare Organization For Identity Providers
        """
        pass

    def test_remove_identity_provider(self) -> None:
        """Test case for remove_identity_provider

        Remove Identity Provider
        """
        pass

    def test_update_identity_provider(self) -> None:
        """Test case for update_identity_provider

        Update Identity Provider
        """
        pass

    def test_validate_access_token(self) -> None:
        """Test case for validate_access_token

        Validate Access Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
