# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.public_images_api import PublicImagesApi


class TestPublicImagesApi(unittest.TestCase):
    """PublicImagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PublicImagesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_public_image(self) -> None:
        """Test case for delete_public_image

        Delete Public Image
        """
        pass

    def test_download_public_image(self) -> None:
        """Test case for download_public_image

        Download Public Image
        """
        pass

    def test_get_public_image_by_id(self) -> None:
        """Test case for get_public_image_by_id

        Get Public Image By Id
        """
        pass

    def test_get_public_images_by_user_id(self) -> None:
        """Test case for get_public_images_by_user_id

        Get Public Images By User Id
        """
        pass

    def test_upload_public_image(self) -> None:
        """Test case for upload_public_image

        Upload Public Image
        """
        pass


if __name__ == '__main__':
    unittest.main()
