# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.organizations_api import OrganizationsApi


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationsApi()

    def tearDown(self) -> None:
        pass

    def test_accept_invitation_to_organization(self) -> None:
        """Test case for accept_invitation_to_organization

        Accept Invitation To Organization
        """
        pass

    def test_change_membership_state(self) -> None:
        """Test case for change_membership_state

        Change Membership State
        """
        pass

    def test_create_organization(self) -> None:
        """Test case for create_organization

        Create Organization
        """
        pass

    def test_delete_organization(self) -> None:
        """Test case for delete_organization

        Delete Organization
        """
        pass

    def test_deny_invitation_to_organization(self) -> None:
        """Test case for deny_invitation_to_organization

        Deny Invitation To Organization
        """
        pass

    def test_get_membership_state(self) -> None:
        """Test case for get_membership_state

        Get Membership State
        """
        pass

    def test_get_my_organizations(self) -> None:
        """Test case for get_my_organizations

        Get All Organizations
        """
        pass

    def test_get_my_organizations_grouped(self) -> None:
        """Test case for get_my_organizations_grouped

        Get All Of Your Organizations Grouped By Membership State
        """
        pass

    def test_get_organization(self) -> None:
        """Test case for get_organization

        Get Organization
        """
        pass

    def test_get_organization_members(self) -> None:
        """Test case for get_organization_members

        Get Organization Members
        """
        pass

    def test_invite_user_to_organization(self) -> None:
        """Test case for invite_user_to_organization

        Invite User To Organization
        """
        pass

    def test_invite_user_to_organization_by_email(self) -> None:
        """Test case for invite_user_to_organization_by_email

        Invite User To Organization By Email
        """
        pass

    def test_leave_organization(self) -> None:
        """Test case for leave_organization

        Leave Organization
        """
        pass

    def test_revoke_user_from_organization(self) -> None:
        """Test case for revoke_user_from_organization

        Revoke User From Organization
        """
        pass

    def test_update_organization(self) -> None:
        """Test case for update_organization

        Update Organization
        """
        pass


if __name__ == '__main__':
    unittest.main()
