# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.log_type import LogType

class TestLogType(unittest.TestCase):
    """LogType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogType(self):
        """Test LogType"""
        # inst = LogType()

if __name__ == '__main__':
    unittest.main()
