# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.login_preparation import LoginPreparation

class TestLoginPreparation(unittest.TestCase):
    """LoginPreparation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoginPreparation:
        """Test LoginPreparation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoginPreparation`
        """
        model = LoginPreparation()
        if include_optional:
            return LoginPreparation(
                organizations = [
                    ugc_guard_python.models.organization_base.OrganizationBase(
                        id = '', 
                        name = '', 
                        description = '', 
                        logo_id = '', 
                        enabled_ai_list = [
                            ''
                            ], 
                        enabled_ai = True, 
                        support_email = '', )
                    ],
                identity_providers = {
                    'key' : [
                        ugc_guard_python.models.identity_provider_base.IdentityProviderBase(
                            id = '', 
                            name = '', 
                            logo_url = '', 
                            enabled = True, )
                        ]
                    }
            )
        else:
            return LoginPreparation(
        )
        """

    def testLoginPreparation(self):
        """Test LoginPreparation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
