# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.modules_api import ModulesApi


class TestModulesApi(unittest.TestCase):
    """ModulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModulesApi()

    def tearDown(self) -> None:
        pass

    def test_create_module(self) -> None:
        """Test case for create_module

        Create Module
        """
        pass

    def test_delete_module(self) -> None:
        """Test case for delete_module

        Delete Module
        """
        pass

    def test_get_all_modules(self) -> None:
        """Test case for get_all_modules

        Get All Modules
        """
        pass

    def test_get_channels_of_module(self) -> None:
        """Test case for get_channels_of_module

        Get Channels Of Module
        """
        pass

    def test_get_mail_settings_of_module(self) -> None:
        """Test case for get_mail_settings_of_module

        Get Mail Settings Of Module
        """
        pass

    def test_get_module_by_id(self) -> None:
        """Test case for get_module_by_id

        Get Module By Id
        """
        pass

    def test_get_module_secret(self) -> None:
        """Test case for get_module_secret

        Get Module Secret
        """
        pass

    def test_get_my_modules(self) -> None:
        """Test case for get_my_modules

        Get My Modules
        """
        pass

    def test_update_mail_settings_of_module(self) -> None:
        """Test case for update_mail_settings_of_module

        Update Mail Settings Of Module
        """
        pass

    def test_update_module(self) -> None:
        """Test case for update_module

        Update Module
        """
        pass


if __name__ == '__main__':
    unittest.main()
