# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.content_api import ContentApi


class TestContentApi(unittest.TestCase):
    """ContentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContentApi()

    def tearDown(self) -> None:
        pass

    def test_create_content(self) -> None:
        """Test case for create_content

        Create Content
        """
        pass

    def test_delete_content(self) -> None:
        """Test case for delete_content

        Delete Content
        """
        pass

    def test_get_all_content_of_report(self) -> None:
        """Test case for get_all_content_of_report

        Get All Content Of Report
        """
        pass

    def test_get_content_by_id(self) -> None:
        """Test case for get_content_by_id

        Get Content By Id
        """
        pass


if __name__ == '__main__':
    unittest.main()
