# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.logs_api import LogsApi


class TestLogsApi(unittest.TestCase):
    """LogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LogsApi()

    def tearDown(self) -> None:
        pass

    def test_get_mail_logs(self) -> None:
        """Test case for get_mail_logs

        Get Mail Logs
        """
        pass

    def test_get_report_logs(self) -> None:
        """Test case for get_report_logs

        Get Report Logs
        """
        pass


if __name__ == '__main__':
    unittest.main()
