# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.webhook_logs_api import WebhookLogsApi


class TestWebhookLogsApi(unittest.TestCase):
    """WebhookLogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhookLogsApi()

    def tearDown(self) -> None:
        pass

    def test_get_webhook_log_by_id(self) -> None:
        """Test case for get_webhook_log_by_id

        Get Webhook Log By Id
        """
        pass

    def test_get_webhook_logs_for_organization(self) -> None:
        """Test case for get_webhook_logs_for_organization

        Get Webhook Logs For Organization
        """
        pass


if __name__ == '__main__':
    unittest.main()
