# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.guards_api import GuardsApi


class TestGuardsApi(unittest.TestCase):
    """GuardsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GuardsApi()

    def tearDown(self) -> None:
        pass

    def test_create_guard(self) -> None:
        """Test case for create_guard

        Create Guard
        """
        pass

    def test_delete_guard(self) -> None:
        """Test case for delete_guard

        Delete Guard
        """
        pass

    def test_enqueue_guard_evaluation(self) -> None:
        """Test case for enqueue_guard_evaluation

        Enqueue Guard Evaluation
        """
        pass

    def test_estimate_tokens_for_guard(self) -> None:
        """Test case for estimate_tokens_for_guard

        Estimate Tokens For Guard
        """
        pass

    def test_get_guard(self) -> None:
        """Test case for get_guard

        Get Guard
        """
        pass

    def test_get_guard_evaluation(self) -> None:
        """Test case for get_guard_evaluation

        Get Guard Evaluation
        """
        pass

    def test_link_rule_to_guard(self) -> None:
        """Test case for link_rule_to_guard

        Link Rule To Guard
        """
        pass

    def test_list_guards(self) -> None:
        """Test case for list_guards

        List Guards
        """
        pass

    def test_unlink_rule_from_guard(self) -> None:
        """Test case for unlink_rule_from_guard

        Unlink Rule From Guard
        """
        pass

    def test_update_guard(self) -> None:
        """Test case for update_guard

        Update Guard
        """
        pass

    def test_update_running_order_of_guard(self) -> None:
        """Test case for update_running_order_of_guard

        Update Running Order Of Guard
        """
        pass


if __name__ == '__main__':
    unittest.main()
