# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.guard_on_fail_action import GuardOnFailAction

class TestGuardOnFailAction(unittest.TestCase):
    """GuardOnFailAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGuardOnFailAction(self):
        """Test GuardOnFailAction"""
        # inst = GuardOnFailAction()

if __name__ == '__main__':
    unittest.main()
