# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.mail_templates_api import MailTemplatesApi


class TestMailTemplatesApi(unittest.TestCase):
    """MailTemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MailTemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_create_mail_template(self) -> None:
        """Test case for create_mail_template

        Create Mail Template
        """
        pass

    def test_delete_mail_template(self) -> None:
        """Test case for delete_mail_template

        Delete Mail Template
        """
        pass

    def test_get_all_mail_templates_for_module_with_defaults(self) -> None:
        """Test case for get_all_mail_templates_for_module_with_defaults

        Get All Mail Templates For Module And All Defaults
        """
        pass

    def test_get_mail_template_by_id(self) -> None:
        """Test case for get_mail_template_by_id

        Get Mail Template By Id
        """
        pass

    def test_get_mail_template_by_type(self) -> None:
        """Test case for get_mail_template_by_type

        Get Mail Template By Type
        """
        pass

    def test_get_mail_templates_for_module(self) -> None:
        """Test case for get_mail_templates_for_module

        Get Mail Templates For Module
        """
        pass

    def test_update_mail_template(self) -> None:
        """Test case for update_mail_template

        Update Mail Template
        """
        pass


if __name__ == '__main__':
    unittest.main()
