# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.body_create_rule import BodyCreateRule

class TestBodyCreateRule(unittest.TestCase):
    """BodyCreateRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyCreateRule:
        """Test BodyCreateRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyCreateRule`
        """
        model = BodyCreateRule()
        if include_optional:
            return BodyCreateRule(
                rule = ugc_guard_python.models.rule.Rule(
                    id = '', 
                    created_at = '', 
                    updated_at = '', 
                    name = '', 
                    description = '', 
                    organization_id = '', 
                    is_deterministic = True, 
                    enabled = True, 
                    deterministic_options_id = '', 
                    non_deterministic_options_id = '', ),
                deterministic_options = ugc_guard_python.models.deterministic_rule_options.DeterministicRuleOptions(
                    id = '', 
                    words = [
                        ''
                        ], 
                    is_blacklist = True, 
                    threshold = 56, 
                    validation_option = 'trigger_on_first_match', ),
                non_deterministic_options = ugc_guard_python.models.non_deterministic_rule_options.NonDeterministicRuleOptions(
                    id = '', 
                    model_name = '', 
                    prompt_template = '', )
            )
        else:
            return BodyCreateRule(
                rule = ugc_guard_python.models.rule.Rule(
                    id = '', 
                    created_at = '', 
                    updated_at = '', 
                    name = '', 
                    description = '', 
                    organization_id = '', 
                    is_deterministic = True, 
                    enabled = True, 
                    deterministic_options_id = '', 
                    non_deterministic_options_id = '', ),
        )
        """

    def testBodyCreateRule(self):
        """Test BodyCreateRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
