# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.ai_usage_cost import AIUsageCost

class TestAIUsageCost(unittest.TestCase):
    """AIUsageCost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AIUsageCost:
        """Test AIUsageCost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AIUsageCost`
        """
        model = AIUsageCost()
        if include_optional:
            return AIUsageCost(
                ai_model = ugc_guard_python.models.ai_model.AiModel(
                    name = '', 
                    enabled = True, 
                    model = '', 
                    description = '', 
                    logo = '', 
                    costs_per_factor_input_tokens = 1.337, 
                    costs_per_factor_output_tokens = 1.337, 
                    factor_tokens = 56, ),
                month = 56,
                year = 56,
                costs = 1.337
            )
        else:
            return AIUsageCost(
                ai_model = ugc_guard_python.models.ai_model.AiModel(
                    name = '', 
                    enabled = True, 
                    model = '', 
                    description = '', 
                    logo = '', 
                    costs_per_factor_input_tokens = 1.337, 
                    costs_per_factor_output_tokens = 1.337, 
                    factor_tokens = 56, ),
                month = 56,
                year = 56,
        )
        """

    def testAIUsageCost(self):
        """Test AIUsageCost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
