# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.identity_provider import IdentityProvider

class TestIdentityProvider(unittest.TestCase):
    """IdentityProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityProvider:
        """Test IdentityProvider
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentityProvider`
        """
        model = IdentityProvider()
        if include_optional:
            return IdentityProvider(
                id = '',
                name = '',
                logo_url = '',
                enabled = True,
                client_id = '',
                client_secret = '',
                discovery_url = '',
                organization_id = '',
                scopes = 'openid profile email',
                auto_create_user = True,
                allow_linking = True,
                identity_token_user_field = 'sub',
                identity_token_email_field = 'email',
                identity_token_username_field = 'preferred_username',
                identity_token_name_field = 'name',
                identity_token_avatar_url_field = 'picture',
                identity_token_channels_mapper_field = 'channels'
            )
        else:
            return IdentityProvider(
                name = '',
                client_id = '',
                client_secret = '',
                discovery_url = '',
                organization_id = '',
        )
        """

    def testIdentityProvider(self):
        """Test IdentityProvider"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
