# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.user_with_identity_providers import UserWithIdentityProviders

class TestUserWithIdentityProviders(unittest.TestCase):
    """UserWithIdentityProviders unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserWithIdentityProviders:
        """Test UserWithIdentityProviders
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserWithIdentityProviders`
        """
        model = UserWithIdentityProviders()
        if include_optional:
            return UserWithIdentityProviders(
                id = '',
                username = '',
                email = '',
                name = '',
                avatar_id = '',
                avatar_url = '',
                identity_providers = [
                    ugc_guard_python.models.user_identity_mapping_with_provider.UserIdentityMappingWithProvider(
                        user_id = '', 
                        identity_provider_id = '', 
                        identity_provider_user_id = '', 
                        identity_provider = ugc_guard_python.models.identity_provider_base.IdentityProviderBase(
                            id = '', 
                            name = '', 
                            logo_url = '', 
                            enabled = True, ), )
                    ]
            )
        else:
            return UserWithIdentityProviders(
                username = '',
                email = '',
        )
        """

    def testUserWithIdentityProviders(self):
        """Test UserWithIdentityProviders"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
