# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.action_history import ActionHistory

class TestActionHistory(unittest.TestCase):
    """ActionHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionHistory:
        """Test ActionHistory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionHistory`
        """
        model = ActionHistory()
        if include_optional:
            return ActionHistory(
                id = '',
                action_id = '',
                content_unique_partner_id = '',
                person_id = '',
                report_id = '',
                performed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                performed_by_id = '',
                success = True
            )
        else:
            return ActionHistory(
                action_id = '',
                person_id = '',
                report_id = '',
                performed_by_id = '',
        )
        """

    def testActionHistory(self):
        """Test ActionHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
