# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.reports_api import ReportsApi


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReportsApi()

    def tearDown(self) -> None:
        pass

    def test_create_magic_report(self) -> None:
        """Test case for create_magic_report

        Create Magic Report
        """
        pass

    def test_create_report(self) -> None:
        """Test case for create_report

        Create Report
        """
        pass

    def test_escalate_report(self) -> None:
        """Test case for escalate_report

        Escalate Report
        """
        pass

    def test_get_all_reports(self) -> None:
        """Test case for get_all_reports

        Get All Reports
        """
        pass

    def test_get_content_of_report(self) -> None:
        """Test case for get_content_of_report

        Get Content Of Report
        """
        pass

    def test_get_enriched_evaluations_of_report(self) -> None:
        """Test case for get_enriched_evaluations_of_report

        Get Enriched Evaluations Of Report
        """
        pass

    def test_get_evaluations_of_report(self) -> None:
        """Test case for get_evaluations_of_report

        Get Evaluations Of Report
        """
        pass

    def test_get_my_reports(self) -> None:
        """Test case for get_my_reports

        Get My Reports
        """
        pass

    def test_get_report_by_id(self) -> None:
        """Test case for get_report_by_id

        Get Report By Id
        """
        pass

    def test_get_reporters_of_report(self) -> None:
        """Test case for get_reporters_of_report

        Get Reporters Of Report
        """
        pass

    def test_reject_report(self) -> None:
        """Test case for reject_report

        Reject Report
        """
        pass

    def test_update_report(self) -> None:
        """Test case for update_report

        Update Report
        """
        pass

    def test_validate_report(self) -> None:
        """Test case for validate_report

        Validate Report
        """
        pass


if __name__ == '__main__':
    unittest.main()
