# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.api.comments_api import CommentsApi


class TestCommentsApi(unittest.TestCase):
    """CommentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_comment(self) -> None:
        """Test case for create_comment

        Create Comment
        """
        pass

    def test_delete_comment(self) -> None:
        """Test case for delete_comment

        Delete Comment
        """
        pass

    def test_get_comment_by_id(self) -> None:
        """Test case for get_comment_by_id

        Get Comment By Id
        """
        pass

    def test_get_comments_by_content_id(self) -> None:
        """Test case for get_comments_by_content_id

        Get Comments By Content Id
        """
        pass

    def test_get_comments_by_report_id(self) -> None:
        """Test case for get_comments_by_report_id

        Get Comments By Report Id
        """
        pass

    def test_update_comment(self) -> None:
        """Test case for update_comment

        Update Comment
        """
        pass


if __name__ == '__main__':
    unittest.main()
