# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.ai_usage import AIUsage

class TestAIUsage(unittest.TestCase):
    """AIUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AIUsage:
        """Test AIUsage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AIUsage`
        """
        model = AIUsage()
        if include_optional:
            return AIUsage(
                organization_id = '',
                month = 56,
                year = 56,
                ai_model = '',
                usage_count = 56
            )
        else:
            return AIUsage(
                organization_id = '',
                month = 56,
                year = 56,
                ai_model = '',
        )
        """

    def testAIUsage(self):
        """Test AIUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
