# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.mail_log_with_invoker import MailLogWithInvoker

class TestMailLogWithInvoker(unittest.TestCase):
    """MailLogWithInvoker unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailLogWithInvoker:
        """Test MailLogWithInvoker
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailLogWithInvoker`
        """
        model = MailLogWithInvoker()
        if include_optional:
            return MailLogWithInvoker(
                id = '',
                created_at = '',
                message = '',
                content = {
                    'key' : null
                    },
                log_type = 'created',
                invoker_id = '',
                organization_id = '',
                email = '',
                successful = True,
                error_message = '',
                hidden = True,
                mail_invoker = ugc_guard_python.models.user_base.UserBase(
                    id = '', 
                    username = '', 
                    email = '', 
                    name = '', 
                    avatar_id = '', 
                    avatar_url = '', )
            )
        else:
            return MailLogWithInvoker(
                email = '',
                successful = True,
                error_message = '',
                hidden = True,
        )
        """

    def testMailLogWithInvoker(self):
        """Test MailLogWithInvoker"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
