# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.compared_module_state import ComparedModuleState

class TestComparedModuleState(unittest.TestCase):
    """ComparedModuleState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComparedModuleState:
        """Test ComparedModuleState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComparedModuleState`
        """
        model = ComparedModuleState()
        if include_optional:
            return ComparedModuleState(
                now = ugc_guard_python.models.module_stats.ModuleStats(
                    module_id = '', 
                    total_reports = 56, 
                    total_files = 56, 
                    total_reporters = 56, 
                    total_actions = 56, 
                    total_performed_actions = 56, 
                    total_types = 56, 
                    total_open_reports = 56, 
                    total_guard_evaluations = 56, 
                    total_guards_evaluations_passed = 56, 
                    total_guards_evaluations_intervened = 56, ),
                prior = ugc_guard_python.models.module_stats.ModuleStats(
                    module_id = '', 
                    total_reports = 56, 
                    total_files = 56, 
                    total_reporters = 56, 
                    total_actions = 56, 
                    total_performed_actions = 56, 
                    total_types = 56, 
                    total_open_reports = 56, 
                    total_guard_evaluations = 56, 
                    total_guards_evaluations_passed = 56, 
                    total_guards_evaluations_intervened = 56, ),
                prior_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ComparedModuleState(
                now = ugc_guard_python.models.module_stats.ModuleStats(
                    module_id = '', 
                    total_reports = 56, 
                    total_files = 56, 
                    total_reporters = 56, 
                    total_actions = 56, 
                    total_performed_actions = 56, 
                    total_types = 56, 
                    total_open_reports = 56, 
                    total_guard_evaluations = 56, 
                    total_guards_evaluations_passed = 56, 
                    total_guards_evaluations_intervened = 56, ),
                prior = ugc_guard_python.models.module_stats.ModuleStats(
                    module_id = '', 
                    total_reports = 56, 
                    total_files = 56, 
                    total_reporters = 56, 
                    total_actions = 56, 
                    total_performed_actions = 56, 
                    total_types = 56, 
                    total_open_reports = 56, 
                    total_guard_evaluations = 56, 
                    total_guards_evaluations_passed = 56, 
                    total_guards_evaluations_intervened = 56, ),
                prior_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testComparedModuleState(self):
        """Test ComparedModuleState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
