# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.type import Type

class TestType(unittest.TestCase):
    """Type unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Type:
        """Test Type
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Type`
        """
        model = Type()
        if include_optional:
            return Type(
                id = '',
                name = '',
                description = '',
                module_id = '',
                is_user_type = True,
                action_secret = ''
            )
        else:
            return Type(
                name = '',
                module_id = '',
        )
        """

    def testType(self):
        """Test Type"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
