# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ugc_guard_python.models.change_password_body import ChangePasswordBody

class TestChangePasswordBody(unittest.TestCase):
    """ChangePasswordBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangePasswordBody:
        """Test ChangePasswordBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangePasswordBody`
        """
        model = ChangePasswordBody()
        if include_optional:
            return ChangePasswordBody(
                old_password = '',
                new_password = ''
            )
        else:
            return ChangePasswordBody(
                new_password = '',
        )
        """

    def testChangePasswordBody(self):
        """Test ChangePasswordBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
