# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AiModel(BaseModel):
    """
    Represents available AI models.  Not a table because it is loaded from the config
    """ # noqa: E501
    name: StrictStr
    enabled: Optional[StrictBool] = False
    model: StrictStr
    description: Optional[StrictStr] = None
    logo: Optional[StrictStr] = None
    costs_per_factor_input_tokens: Optional[Union[StrictFloat, StrictInt]] = 0.0
    costs_per_factor_output_tokens: Optional[Union[StrictFloat, StrictInt]] = 0.0
    factor_tokens: Optional[StrictInt] = 1000
    __properties: ClassVar[List[str]] = ["name", "enabled", "model", "description", "logo", "costs_per_factor_input_tokens", "costs_per_factor_output_tokens", "factor_tokens"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AiModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if logo (nullable) is None
        # and model_fields_set contains the field
        if self.logo is None and "logo" in self.model_fields_set:
            _dict['logo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AiModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else False,
            "model": obj.get("model"),
            "description": obj.get("description"),
            "logo": obj.get("logo"),
            "costs_per_factor_input_tokens": obj.get("costs_per_factor_input_tokens") if obj.get("costs_per_factor_input_tokens") is not None else 0.0,
            "costs_per_factor_output_tokens": obj.get("costs_per_factor_output_tokens") if obj.get("costs_per_factor_output_tokens") is not None else 0.0,
            "factor_tokens": obj.get("factor_tokens") if obj.get("factor_tokens") is not None else 1000
        })
        return _obj


