# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MailTemplateType(str, Enum):
    """
    Enum for MailTemplateType. The type of mail template.
    """

    """
    allowed enum values
    """
    REPORT_CREATED_ADMIN = 'report_created_admin'
    REPORT_CREATED_USER = 'report_created_user'
    REPORT_RESOLVED_USER = 'report_resolved_user'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MailTemplateType from a JSON string"""
        return cls(json.loads(json_str))


