# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ModuleStats(BaseModel):
    """
    Represents statistics for a module.
    """ # noqa: E501
    module_id: StrictStr
    total_reports: Optional[StrictInt] = 0
    total_files: Optional[StrictInt] = 0
    total_reporters: Optional[StrictInt] = 0
    total_actions: Optional[StrictInt] = 0
    total_types: Optional[StrictInt] = 0
    total_open_reports: Optional[StrictInt] = 0
    __properties: ClassVar[List[str]] = ["module_id", "total_reports", "total_files", "total_reporters", "total_actions", "total_types", "total_open_reports"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModuleStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModuleStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "module_id": obj.get("module_id"),
            "total_reports": obj.get("total_reports") if obj.get("total_reports") is not None else 0,
            "total_files": obj.get("total_files") if obj.get("total_files") is not None else 0,
            "total_reporters": obj.get("total_reporters") if obj.get("total_reporters") is not None else 0,
            "total_actions": obj.get("total_actions") if obj.get("total_actions") is not None else 0,
            "total_types": obj.get("total_types") if obj.get("total_types") is not None else 0,
            "total_open_reports": obj.get("total_open_reports") if obj.get("total_open_reports") is not None else 0
        })
        return _obj


