# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ugc_guard_python.models.user_organization_membership_state import UserOrganizationMembershipState
from typing import Optional, Set
from typing_extensions import Self

class OrgWithMembershipState(BaseModel):
    """
    A class to represent an organization with its membership state.
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: StrictStr
    description: Optional[StrictStr] = None
    logo_id: Optional[StrictStr]
    enabled_ai_list: Optional[List[StrictStr]] = None
    enabled_ai: Optional[StrictBool] = None
    support_email: Optional[StrictStr] = None
    membership_state: UserOrganizationMembershipState
    __properties: ClassVar[List[str]] = ["id", "name", "description", "logo_id", "enabled_ai_list", "enabled_ai", "support_email", "membership_state"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrgWithMembershipState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if logo_id (nullable) is None
        # and model_fields_set contains the field
        if self.logo_id is None and "logo_id" in self.model_fields_set:
            _dict['logo_id'] = None

        # set to None if enabled_ai (nullable) is None
        # and model_fields_set contains the field
        if self.enabled_ai is None and "enabled_ai" in self.model_fields_set:
            _dict['enabled_ai'] = None

        # set to None if support_email (nullable) is None
        # and model_fields_set contains the field
        if self.support_email is None and "support_email" in self.model_fields_set:
            _dict['support_email'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrgWithMembershipState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "logo_id": obj.get("logo_id"),
            "enabled_ai_list": obj.get("enabled_ai_list"),
            "enabled_ai": obj.get("enabled_ai"),
            "support_email": obj.get("support_email"),
            "membership_state": obj.get("membership_state")
        })
        return _obj


