# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ReportCategory(str, Enum):
    """
    Enum for ReportCategory. The category of a report.
    """

    """
    allowed enum values
    """
    HATE_SPEECH = 'hate_speech'
    SPAM = 'spam'
    HARASSMENT = 'harassment'
    PORNOGRAPHY = 'pornography'
    CHILD_ENDANGERMENT = 'child_endangerment'
    DISINFORMATION = 'disinformation'
    VIOLENCE = 'violence'
    SELF_HARM = 'self_harm'
    SCAM = 'scam'
    ILLEGAL_CONTENT = 'illegal_content'
    OTHER = 'other'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ReportCategory from a JSON string"""
        return cls(json.loads(json_str))


