# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ugc_guard_python.models.ai_evaluation import AIEvaluation
from ugc_guard_python.models.report_state import ReportState
from ugc_guard_python.models.reporters_with_person import ReportersWithPerson
from typing import Optional, Set
from typing_extensions import Self

class ReportWithReportersAndEvaluations(BaseModel):
    """
    Report with reporters information.
    """ # noqa: E501
    description: Optional[StrictStr] = None
    module_id: StrictStr
    type_id: StrictStr
    id: Optional[StrictStr] = None
    report_state: Optional[ReportState] = None
    main_content_id: StrictStr
    reported_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    secret: Optional[StrictStr] = None
    reporters: Optional[List[ReportersWithPerson]] = None
    evaluations: Optional[List[AIEvaluation]] = None
    __properties: ClassVar[List[str]] = ["description", "module_id", "type_id", "id", "report_state", "main_content_id", "reported_at", "updated_at", "secret", "reporters", "evaluations"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReportWithReportersAndEvaluations from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in reporters (list)
        _items = []
        if self.reporters:
            for _item_reporters in self.reporters:
                if _item_reporters:
                    _items.append(_item_reporters.to_dict())
            _dict['reporters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in evaluations (list)
        _items = []
        if self.evaluations:
            for _item_evaluations in self.evaluations:
                if _item_evaluations:
                    _items.append(_item_evaluations.to_dict())
            _dict['evaluations'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReportWithReportersAndEvaluations from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "module_id": obj.get("module_id"),
            "type_id": obj.get("type_id"),
            "id": obj.get("id"),
            "report_state": obj.get("report_state"),
            "main_content_id": obj.get("main_content_id"),
            "reported_at": obj.get("reported_at"),
            "updated_at": obj.get("updated_at"),
            "secret": obj.get("secret"),
            "reporters": [ReportersWithPerson.from_dict(_item) for _item in obj["reporters"]] if obj.get("reporters") is not None else None,
            "evaluations": [AIEvaluation.from_dict(_item) for _item in obj["evaluations"]] if obj.get("evaluations") is not None else None
        })
        return _obj


