# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Rule(BaseModel):
    """
    Base model for a rule.  If a rule is non-deterministic, it will lead to an AIEvaluation object If a rule is deterministic, it will lead to a DeterministicEvaluation
    """ # noqa: E501
    id: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = Field(default=None, description="Creation timestamp in ISO format")
    updated_at: Optional[StrictStr] = None
    name: Optional[StrictStr] = Field(default=None, description="Name of the rule, e.g., 'Spam Filter', 'Content Classifier', etc.")
    description: Optional[StrictStr] = None
    organization_id: Optional[StrictStr] = None
    is_deterministic: Optional[StrictBool] = Field(default=True, description="Indicates whether the rule is deterministic (e.g., black/whitelist) or non-deterministic (e.g., AI model)")
    enabled: Optional[StrictBool] = Field(default=True, description="Indicates whether the rule is currently enabled or disabled")
    deterministic_options_id: Optional[StrictStr] = None
    non_deterministic_options_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "created_at", "updated_at", "name", "description", "organization_id", "is_deterministic", "enabled", "deterministic_options_id", "non_deterministic_options_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Rule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if organization_id (nullable) is None
        # and model_fields_set contains the field
        if self.organization_id is None and "organization_id" in self.model_fields_set:
            _dict['organization_id'] = None

        # set to None if deterministic_options_id (nullable) is None
        # and model_fields_set contains the field
        if self.deterministic_options_id is None and "deterministic_options_id" in self.model_fields_set:
            _dict['deterministic_options_id'] = None

        # set to None if non_deterministic_options_id (nullable) is None
        # and model_fields_set contains the field
        if self.non_deterministic_options_id is None and "non_deterministic_options_id" in self.model_fields_set:
            _dict['non_deterministic_options_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Rule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "organization_id": obj.get("organization_id"),
            "is_deterministic": obj.get("is_deterministic") if obj.get("is_deterministic") is not None else True,
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "deterministic_options_id": obj.get("deterministic_options_id"),
            "non_deterministic_options_id": obj.get("non_deterministic_options_id")
        })
        return _obj


