# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class UserOrganizationMembershipState(str, Enum):
    """
    Enum for UserOrganizationMembershipState. The state of a user's membership in an organization.
    """

    """
    allowed enum values
    """
    INVITED = 'invited'
    REVIEWER = 'reviewer'
    MEMBER = 'member'
    ADMIN = 'admin'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserOrganizationMembershipState from a JSON string"""
        return cls(json.loads(json_str))


