# coding: utf-8

"""
    UGC Guard API

    API for UGC Guard. A tool to help you manage reports on user generated content.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class WebhookLog(BaseModel):
    """
    Log model for webhook invocations.
    """ # noqa: E501
    id: Optional[StrictStr] = None
    description: StrictStr = Field(description="Webhook description")
    invoked_at: Optional[datetime] = Field(default=None, description="The time the webhook was invoked")
    status_code: StrictInt = Field(description="The HTTP status code returned by the webhook endpoint")
    request_url: StrictStr = Field(description="The URL to which the webhook request was sent")
    webhook_method: Annotated[str, Field(strict=True, max_length=7)] = Field(description="The HTTP method used for the webhook request (e.g., POST, GET)")
    successful: StrictBool = Field(description="Whether the webhook invocation was successful (2xx status code)")
    error_message: Optional[StrictStr] = None
    response_body: Optional[StrictStr] = None
    response_headers: Optional[Dict[str, Any]] = None
    request_headers: Optional[Dict[str, Any]] = None
    payload: Optional[Dict[str, Any]] = None
    organization_id: Optional[StrictStr] = None
    action_history_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "description", "invoked_at", "status_code", "request_url", "webhook_method", "successful", "error_message", "response_body", "response_headers", "request_headers", "payload", "organization_id", "action_history_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookLog from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if response_body (nullable) is None
        # and model_fields_set contains the field
        if self.response_body is None and "response_body" in self.model_fields_set:
            _dict['response_body'] = None

        # set to None if response_headers (nullable) is None
        # and model_fields_set contains the field
        if self.response_headers is None and "response_headers" in self.model_fields_set:
            _dict['response_headers'] = None

        # set to None if request_headers (nullable) is None
        # and model_fields_set contains the field
        if self.request_headers is None and "request_headers" in self.model_fields_set:
            _dict['request_headers'] = None

        # set to None if payload (nullable) is None
        # and model_fields_set contains the field
        if self.payload is None and "payload" in self.model_fields_set:
            _dict['payload'] = None

        # set to None if organization_id (nullable) is None
        # and model_fields_set contains the field
        if self.organization_id is None and "organization_id" in self.model_fields_set:
            _dict['organization_id'] = None

        # set to None if action_history_id (nullable) is None
        # and model_fields_set contains the field
        if self.action_history_id is None and "action_history_id" in self.model_fields_set:
            _dict['action_history_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookLog from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "description": obj.get("description"),
            "invoked_at": obj.get("invoked_at"),
            "status_code": obj.get("status_code"),
            "request_url": obj.get("request_url"),
            "webhook_method": obj.get("webhook_method"),
            "successful": obj.get("successful"),
            "error_message": obj.get("error_message"),
            "response_body": obj.get("response_body"),
            "response_headers": obj.get("response_headers"),
            "request_headers": obj.get("request_headers"),
            "payload": obj.get("payload"),
            "organization_id": obj.get("organization_id"),
            "action_history_id": obj.get("action_history_id")
        })
        return _obj


